### ISSUE TITLE
Is it possible to send messages back from the mobile App -> Server?

### ISSUE THREAD

**Issue by afomera** [hotwired/hotwire-native-bridge#2]
Hey folks!

Was giving Hotwire Native a try and ran into something I'm not sure is possible, but thought it might be a future enhancement that could be useful (if it was possible).

In my case I have a native audio player + bridge component and I was hoping to find a way to notify the Web about an event that completed on the Native side of things (in my case when a song ends, so I could trigger it to go to the next song), but didn't seem to find a way to notify the JS / listen on the JS for the event to happen.

If I'm overlooking something let me know, but I think this might be a useful addition if it's within the scope of things.

Thanks!

**Comment by jayohms** [comment]
A native bridge component needs to correspond to a web component present in the webview. The native component must receive at least one `message` from the web component before it's active. One thing we've done in our apps is have a global `page` component that sends a `"connect"` message on every page through the Rails app. That way, the native  `PageComponent` can communicate with the webview on any page throughout the app.

From there, you can use reply back to the `page` web component with a message containing any arbitrary json data. On iOS, it'd look like:
```swift
reply(
  to: "connect",
  with: myMessageWithData
)
```

You can see an an example in the demo app how to [reply back to a component with data](https://github.com/hotwired/hotwire-native-ios/blob/aa5da14014143be76e7856f2bf07cf887fb7bfe0/Demo/Bridge/MenuComponent.swift#L63-L68). Does that answer your question?

**Comment by afomera** [comment]
Rails dev masquerading as a mobile dev here (with virtually no experience) 😅, I think that makes sense I've just not been able to connect the dots for me yet, I'll give this a try and see if I can make something work. 🙏 Thanks! It gives me a direction to poke in until I can make something work.

**Comment by jayohms** [comment]
No worries, the demo iOS/Android apps are a great place to understand how they work and try out modifications:

- iOS: https://github.com/hotwired/hotwire-native-ios/tree/main/Demo
- Android: https://github.com/hotwired/hotwire-native-android/tree/main/demo
- Web: https://github.com/hotwired/hotwire-native-demo/tree/main/public/javascript/controllers/bridge

There's also plenty of example online examples for building "Strada" components, which was the prior name in a separate library before merging them into Hotwire Native as "bridge components".
